name: "Test"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 1 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - run: ./steps.sh
